# -*- coding: utf-8 -*-
"""Lesson7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohzDS0r-EBuxhXoTnTgKEtofuThGtYaB

# Робота з файлами в Python

## Створення файлу, запис
"""

# Відкриваємо файл у режимі запису ("w")
# 'r' - читання (за замовчуванням). Файл має існувати.
# 'w' - запис. Створює новий файл або перезаписує той, що вже існує.
# 'a' - додавання. Дописує в кінець файлу, не перезаписуючи його.
# 'b' - бінарний режим (може бути використаний разом з іншими, наприклад 'rb' або 'wb').
# '+' - оновлення (читання та запис).


f = open("one_line.txt", "w", encoding="utf-8")


# Записуємо одну строку
f.write("Це одна строка тексту.\n")

# Закриваємо файл
f.close()

f = open("multi_lines.txt", "w", encoding="utf-8")

f.write("Перша строка.\n")
f.write("Друга строка.\n")
f.write("Третя строка.\n")

f.close()

f = open("multi_lines_loop.txt", "w", encoding="utf-8")

for i in range(1, 6):
    f.write("Строка номер " + str(i) + "\n")

f.close()

f = open("chars.txt", "w", encoding="utf-8")

f.write("A")
f.write("Б")
f.write("\n")
f.write("123")

f.close()

f = open("numbers.txt", "w", encoding="utf-8")

x = 42
y = 3.14159


f.write(str(x) + "\n")
f.write(str(y) + "\n")

f.close()

f = open("numbers_loop.txt", "w", encoding="utf-8")

for i in range(1, 6):
    square = i * i
    f.write("i = " + str(i) + ", i^2 = " + str(square) + "\n")

f.close()





"""## Відкриття файлу, читання"""

s = "Привіт\nсвіт"
print(s)
print(repr(s))

f = open("one_line.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Вміст one_line.txt:")
print(repr(content))

f = open("multi_lines.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Сирий вміст multi_lines.txt:")
print(repr(content))

# список рядків:
lines = content.splitlines()

print("\nРядки окремо:")
for i, line in enumerate(lines, start=1):
    print(f"Рядок {i}: {line}")

f = open("multi_lines_loop.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Сирий вміст multi_lines_loop.txt:")
print(repr(content))

lines = content.splitlines()

print("\nРядки з циклу:")
for line in lines:
    print(line)

f = open("chars.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Вміст chars.txt (рядком):")
print(repr(content))

print("\nПо-символьно:")
for ch in content:
    print(f"Символ: {repr(ch)}")

f = open("numbers.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Сирий вміст numbers.txt:")
print(repr(content))

lines = content.splitlines()   # кожен рядок окремо
print("\nРядки з числами:", lines)

# Перетворення рядків у числа (float)
nums = []
for s in lines:
    if s.strip() != "":
        nums.append(float(s.strip()))

print("Числа як float:", nums)
if nums:
    print("Сума чисел:", sum(nums))



f = open("numbers_loop.txt", "r", encoding="utf-8")

content = f.read()

f.close()

print("Сирий вміст numbers_loop.txt:")
print(repr(content))

lines = content.splitlines()

print("\nРядки з файлу:")
for line in lines:
    print(line)

print("\nОбробка рядків (витягуємо числа):")
for line in lines:

    clean = line.replace(",", "")
    parts = clean.split()   # ["i", "=", "1", "i^2", "=", "1"]

    try:
        i_value = int(parts[2])
        square_value = int(parts[-1])
        print(f"i = {i_value}, i^2 = {square_value}")
    except (IndexError, ValueError):
        print("Не вдалося розібрати рядок:", line)



fh = open('test.txt', 'w')
fh.write('first line\nsecond line\nthird line')
fh.close()

fh = open('test.txt', 'r')
while True:
    line = fh.readline()
    if not line:
        break
    print(line)

fh.close()



fh = open('test.txt', 'w')
fh.write('first line\nsecond line\nthird line')
fh.close()

fh = open('test.txt', 'r')
lines = fh.readlines()
print(lines)

fh.close()



fh = open("test.txt", "w")
fh.write("first line\nsecond line\nthird line")
fh.close()

fh = open("test.txt", "r")
lines = [el.strip() for el in fh.readlines()]
print(lines)

fh.close()





"""## Позиції курсора у файлі"""

fh = open('test.txt', 'w+')
fh.write('hello!')

fh.seek(1)
second = fh.read(1)
print(second)  # 'e'

fh.close()



fh = open("test.txt", "w+")
fh.write("hello!")

position = fh.tell()
print(position)  # 6

fh.seek(1)
position = fh.tell()
print(position)  # 1

fh.read(2)
position = fh.tell()
print(position)  # 3

fh.close()





"""## Менеджер контексту `with`"""

with open("test.txt", "w") as fh:
    fh.write("first line\nsecond line\nthird line")

with open("test.txt", "r") as fh:
    lines = [el.strip() for el in fh.readlines()]

print(lines)

with open("one_line.txt", "r", encoding="utf-8") as f:
    content = f.read()

print("Вміст one_line.txt:")
print(repr(content))

with open("multi_lines.txt", "r", encoding="utf-8") as f:
    content = f.read()   # весь файл в один рядок

print("Сирий вміст multi_lines.txt:")
print(repr(content))

lines = content.splitlines()

print("\nРядки окремо:")
for i, line in enumerate(lines, start=1):
    print(f"Рядок {i}: {line}")

with open("multi_lines_loop.txt", "r", encoding="utf-8") as f:
    content = f.read()

print("Сирий вміст multi_lines_loop.txt:")
print(repr(content))

lines = content.splitlines()

print("\nРядки з циклу:")
for line in lines:
    print(line)

with open("chars.txt", "r", encoding="utf-8") as f:
    content = f.read()

print("Вміст chars.txt (рядком):")
print(repr(content))

print("\nПо-символьно:")
for ch in content:
    print(f"Символ: {repr(ch)}")

with open("numbers.txt", "r", encoding="utf-8") as f:
    content = f.read()

print("Сирий вміст numbers.txt:")
print(repr(content))

lines = content.splitlines()   # кожен рядок окремо
print("\nРядки з числами:", lines)

# Перетворення рядків у числа (float)
nums = []
for s in lines:
    if s.strip() != "":
        nums.append(float(s.strip()))

print("Числа як float:", nums)
if nums:
    print("Сума чисел:", sum(nums))

with open("numbers_loop.txt", "r", encoding="utf-8") as f:
    content = f.read()

print("Сирий вміст numbers_loop.txt:")
print(repr(content))

lines = content.splitlines()

print("\nРядки з файлу:")
for line in lines:
    print(line)

print("\nОбробка рядків (витягуємо числа):")
for line in lines:
    clean = line.replace(",", "")
    parts = clean.split()   # ["i", "=", "1", "i^2", "=", "1"]

    try:
        i_value = int(parts[2])
        square_value = int(parts[-1])
        print(f"i = {i_value}, i^2 = {square_value}")
    except (IndexError, ValueError):
        print("Не вдалося розібрати рядок:", line)

"""## Запис словника

текстовий файл
"""

user = {
    "name": "Oleksii",
    "age": 20,
    "skills": ["Python", "Data Analysis", "Machine Learning"],
    "active": True
}

with open("user_dict.txt", "w", encoding="utf-8") as f:
    f.write(str(user))

print("Словник записано у файл user_dict.txt")

"""JSON"""

import json

user = {
    "name": "Oleksii",
    "age": 20,
    "skills": ["Python", "Data Analysis", "Machine Learning"],
    "active": True
}

# Запис у файл у форматі JSON
with open("user_dict.json", "w", encoding="utf-8") as f:
    json.dump(user, f, ensure_ascii=False, indent=4)

print("Словник записано у файл user_dict.json у форматі JSON")

import ast

with open("user_dict.txt", "r", encoding="utf-8") as f:
    text = f.read()

print("Сирий текст з файлу:")
print(text)

# Перетворюємо текст у словник
user_from_text = ast.literal_eval(text)

print("\nТип:", type(user_from_text))
print("Словник:", user_from_text)
print("Ім'я:", user_from_text["name"])
print("Скіли:", user_from_text["skills"])

import json

with open("user_dict.json", "r", encoding="utf-8") as f:
    user_from_json = json.load(f)

print("Тип:", type(user_from_json))
print("Словник з JSON:")
print(user_from_json)

print("\nОкремі поля:")
print("Ім'я:", user_from_json["name"])
print("Вік:", user_from_json["age"])
print("Активний?:", user_from_json["active"])
print("Кількість скілів:", len(user_from_json["skills"]))

"""## Байтові рядки `bytes`"""

filename = "example_bytes.bin"

# Запис байтів
data = b"Hello\x00\x01\x02World"

with open(filename, "wb") as f:
    f.write(data)

print("Байтовий файл записано:", filename)

filename = "example_bytes.bin"

with open(filename, "rb") as f:
    content = f.read()    # повертає bytes

print("Тип:", type(content))
print("Вміст як bytes:", content)
print("Довжина (байт):", len(content))



filename = "text_utf8.bin"

text = "Привіт, світ!##$#"

data = text.encode("utf-8")

with open(filename, "wb") as f:
    f.write(data)

print("Записано байтове представлення тексту у файл:", filename)
print("Байти:", data)

filename = "text_utf8.bin"

with open(filename, "rb") as f:
    data = f.read()      # bytes

print("Зчитані байти:", data)
text_back = data.decode("utf-8")
print("Після decode UTF-8:", text_back)

"""## Модуль `os`

### Поточна директорія
"""

import os

# Поточна робоча директорія
print(os.getcwd())

import os

print("Було:", os.getcwd())

new_dir = "data"

if os.path.isdir(new_dir):
    os.chdir(new_dir)
    print("Стало:", os.getcwd())
else:
    print(f"Папки '{new_dir}' не існує")

"""### Змінні середовища (os.environ)"""

import os

# Отримати всі змінні середовища як словник
env = os.environ

print(env)

# Взяти конкретну змінну
home = os.environ.get("HOME")
print("HOME =", home)

# Встановити змінну середовища (працює в рамках поточного процесу)
os.environ["MY_VAR"] = "test_value"
print(os.environ["MY_VAR"])



"""## `shutil` – копіювання, переміщення, видалення, архіви.

### створення структури каталогів і файлів
"""

import os
import shutil
from pathlib import Path

# Базова директорія для прикладів
base_dir = Path("demo_fs")
shutil.rmtree(base_dir, ignore_errors=True)
base_dir.mkdir(parents=True, exist_ok=True)

# Підпапки
src_dir = base_dir / "src"
dst_dir = base_dir / "dst"
src_dir.mkdir()
dst_dir.mkdir()

# Створимо кілька файлів у src_dir
file1 = src_dir / "file1.txt"
file2 = src_dir / "file2.txt"

file1.write_text("Це вміст file1.txt\nДругий рядок\n", encoding="utf-8")
file2.write_text("Це вміст file2.txt\n", encoding="utf-8")

print("Структура для прикладів створена:", base_dir.resolve())





"""### Копіювання файлів"""

import shutil
from pathlib import Path

src_file = base_dir / "src" / "file1.txt"
copied_file = base_dir / "dst" / "file1_copy.txt"

# Просте копіювання (вміст + права доступу)
shutil.copy(src_file, copied_file)

print("Скопійовано файл:", copied_file)

# Копіювання з метаданими (час створення, модифікації і т.д.)
copied_file2 = base_dir / "dst" / "file1_copy2.txt"
shutil.copy2(src_file, copied_file2)

print("Скопійовано файл з метаданими:", copied_file2)

"""### Копіювання папки"""

src_folder = base_dir / "src"
copy_folder = base_dir / "src_copy"

# Якщо папка вже існує — спочатку видаляє
shutil.rmtree(copy_folder, ignore_errors=True)

shutil.copytree(src_folder, copy_folder)

print("Папку скопійовано як:", copy_folder)
print("Вміст:", list(copy_folder.iterdir()))

"""### Переміщення / перейменування"""

# Перемістимо file2.txt з src у dst
file2_src = base_dir / "src" / "file2.txt"
file2_dst = base_dir / "dst" / "file2_moved.txt"

moved_path = shutil.move(str(file2_src), str(file2_dst))
print("Файл переміщено в:", moved_path)







"""### Видалення дерева каталогів"""

temp_dir = base_dir / "temp_dir"
temp_dir.mkdir(exist_ok=True)
(temp_dir / "temp.txt").write_text("Тимчасовий файл", encoding="utf-8")

print("Створили тимчасову папку:", temp_dir)

# Рекурсивне видалення всієї папки
shutil.rmtree(temp_dir)

print("Папку temp_dir видалено (існує?):", temp_dir.exists())





"""### Створення архіву і розпакування"""

archive_base_name = base_dir / "src_archive"  # без розширення
archive_format = "zip"  # 'zip', 'tar', 'gztar', 'bztar', 'xztar'

# Створюємо архів з папки src_dir
archive_path = shutil.make_archive(
    base_name=str(archive_base_name),
    format=archive_format,
    root_dir=str(src_dir)
)

print("Архів створено:", archive_path)

# Розпакуємо архів у нову папку
unpack_dir = base_dir / "unpacked_src"
shutil.unpack_archive(archive_path, unpack_dir)

print("Архів розпаковано в:", unpack_dir)
print("Вміст розпакованої папки:", list(unpack_dir.iterdir()))







"""## `pathlib` – директорії, шляхи, фільтрація файлів, операції з файлами.

### Базові операції з `Path`
"""

from pathlib import Path

p = base_dir / "src" / "file1.txt"

print("Об'єкт Path:", p)
print("Розширення:", p.suffix)
print("Ім'я файлу:", p.name)
print("Батьківська папка:", p.parent)
print("Абсолютний шлях:", p.resolve())
print("Чи існує файл?:", p.exists())
print("Це файл?:", p.is_file())
print("Це директорія?:", p.is_dir())

"""### Перелік вмісту директорії, фільтрація по розширенню"""

src_dir = base_dir / "src"

print("Вміст папки src:")
for item in src_dir.iterdir():
    print(" -", item, "| файл?" , item.is_file(), "| папка?", item.is_dir())

# Всі .txt файли в demo_fs (рекурсивно)
print("\nУсі .txt файли в demo_fs (рекурсивно):")
for path in base_dir.rglob("*.txt"):
    print(" -", path)

"""### Створення, перейменування, видалення файлів і папок через `pathlib`"""

# Створення нової папки
new_dir = base_dir / "new_folder"
new_dir.mkdir(exist_ok=True)
print("Створено папку:", new_dir)

# Створення нового файлу
new_file = new_dir / "note.txt"
new_file.write_text("Привіт з pathlib!\n", encoding="utf-8")
print("Створено файл:", new_file)

# Перейменування файлу
renamed_file = new_dir / "renamed_note.txt"
new_file.rename(renamed_file)
print("Файл перейменовано в:", renamed_file)

# Видалення файлу
renamed_file.unlink()
print("Файл видалено (існує?):", renamed_file.exists())





"""## Читання/запис файлів через `pathlib.Path`

Текстові файли: `write_text`, `read_text`
"""

text_path = base_dir / "demo_text.txt"

# Запис тексту
text_content = "Це приклад запису тексту через Path.write_text.\nЩе один рядок."
text_path.write_text(text_content, encoding="utf-8")

# Читання тексту
read_back = text_path.read_text(encoding="utf-8")

print("Прочитаний текст:")
print(read_back)

"""Байтові файли: `write_bytes`, `read_bytes`"""

binary_path = base_dir / "demo_bytes.bin"

# Дані у вигляді bytes
data = b"\x01\x02\x03Hello\xff"

# Запис байтів
binary_path.write_bytes(data)

# Читання байтів
read_bytes = binary_path.read_bytes()

print("Прочитані байти:", read_bytes)
print("Тип:", type(read_bytes), ", довжина:", len(read_bytes))

